 ## بسم الله الرحمن الرحيم

In [12]:
!pip install pandas --quiet

In [2]:
import numpy as pd
print(pd.__version__)

2.3.5

In [14]:
s = pd.Series([1,2,3,4])
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [19]:
dates = pd.date_range("2005-06-21", periods=6)
print(dates)

DatetimeIndex(['2005-06-21', '2005-06-22', '2005-06-23', '2005-06-24',
               '2005-06-25', '2005-06-26'],
              dtype='datetime64[ns]', freq='D')

In [25]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("2005-06-21"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),   # changed to 4 elements
        "E": pd.Categorical(["test","train","test","train"]),
        "F": "Foo"
    }
)

df
print(df)

     A          B    C  D      E    F
0  1.0 2005-06-21  1.0  3   test  Foo
1  1.0 2005-06-21  1.0  3  train  Foo
2  1.0 2005-06-21  1.0  3   test  Foo
3  1.0 2005-06-21  1.0  3  train  Foo

In [26]:
df.head()

     A          B    C  D      E    F
0  1.0 2005-06-21  1.0  3   test  Foo
1  1.0 2005-06-21  1.0  3  train  Foo
2  1.0 2005-06-21  1.0  3   test  Foo
3  1.0 2005-06-21  1.0  3  train  Foo

In [27]:
df.tail()

     A          B    C  D      E    F
0  1.0 2005-06-21  1.0  3   test  Foo
1  1.0 2005-06-21  1.0  3  train  Foo
2  1.0 2005-06-21  1.0  3   test  Foo
3  1.0 2005-06-21  1.0  3  train  Foo

In [32]:
df.index
print(df.index)

Index([0, 1, 2, 3], dtype='int64')

In [33]:
df.to_numpy()

array([[1.0, Timestamp('2005-06-21 00:00:00'), 1.0, 3, 'test', 'Foo'],
       [1.0, Timestamp('2005-06-21 00:00:00'), 1.0, 3, 'train', 'Foo'],
       [1.0, Timestamp('2005-06-21 00:00:00'), 1.0, 3, 'test', 'Foo'],
       [1.0, Timestamp('2005-06-21 00:00:00'), 1.0, 3, 'train', 'Foo']],
      dtype=object)

In [3]:
import pandas as pd
df=pd.read_csv("sales_data_sample.csv", encoding = "latin1")
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [1]:
df.head()

NameError: name 'df' is not defined